[package]
name = "qw-renderer-gl"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
qw-common = { path = "../qw-common" }
glow = { version = "0.16.0", optional = true }

[features]
default = []
glow = ["dep:glow"]
