[package]
name = "qw-window-glfw"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
glfw = { version = "0.61.0", optional = true }

[features]
default = []
glfw = ["dep:glfw"]
